### ISSUE TITLE
Section 1.6 Incorrect "Players attacking and killing things" code snippet

### ISSUE THREAD

**Issue by RohitJones** [thebracket/rustrogueliketutorial#100]
The 2nd code snippet under the "[Players attacking and killing things](https://bfnightly.bracketproductions.com/rustbook/chapter_7.html#player-attacking-and-killing-things)" header, referring to the addition of WantsToMelee to the player movement seems to be incorrect and instead contains code relevant to monsters attacking the player.

Thank you for this amazing tutorial !

**Comment by workingjubilee** [comment]
This issue can be closed.
