### ISSUE TITLE
Section 1.6 Incorrect "letting the monsters hit you back" code snippet

### ISSUE THREAD

**Issue by RohitJones** [thebracket/rustrogueliketutorial#101]
In the 3rd code snippet under the "[Letting the monsters hit you back](https://bfnightly.bracketproductions.com/rustbook/chapter_7.html#letting-the-monsters-hit-you-back)" header, the following lines of code are incorrect as we have not yet inserted RunState into the ecs. (The additional run states are introduced and inserted into the ecs under the subsequent header "Expanding the turn system" )

```rust    
type SystemData = ( ...
                    ReadExpect<'a, RunState>,
                    ...);
```
```rust
if *runstate != RunState::MonsterTurn { return; }
```
Thank you for this amazing tutorial !

**Comment by thebracket** [comment]
Thanks! I'll see about getting this cleaned up today.

**Comment by workingjubilee** [comment]
This issue can be closed.
