### ISSUE TITLE
Not all simultaneous damage hits on the Player get processed correctly.

### ISSUE THREAD

**Issue by NielsRenard** [thebracket/rustrogueliketutorial#103]
When the player gets hit by multiple damage sources during one "tick", not all of them get processed.

Convoluted example (I skip a turn at the start):
![Gif from 2020-03-01 21-32 (multiple_damage_sources_bug)](https://user-images.githubusercontent.com/34090207/75711118-1d1de580-5cc6-11ea-831f-d14ab3abc6b5.gif)

Running native, using the chapter-18 code from the tutorial (to make sure it wasn't something I introduced) : 

![Gif from 2020-03-02 20-54(multi_damage_bug)](https://user-images.githubusercontent.com/34090207/75712476-463f7580-5cc8-11ea-8f31-57e64aec11f7.gif)

Comparing multi damage source versus single damage source:
![Gif from 2020-03-02 20-58(compare_multi_damage_to_single_damage_fireball)](https://user-images.githubusercontent.com/34090207/75712780-cb2a8f00-5cc8-11ea-8225-3d26eb423925.gif)

**Comment by NielsRenard** [comment]
I think the Player Entity gets inserted into SuffersDamage once for the fireball AoE, and once right after, for the melee combat hit. Maybe specs overwrites it before the damage system can process it? https://docs.rs/specs/0.16.1/specs/struct.World.html?search=#method.insert

Going to debug it a bit more.

**Comment by thebracket** [comment]
Specs does indeed overwrite it, not wanting more than one of the same component type. It's a pitfall of the ECS I hadn't run into before. After chapter 63, damage moves into the "effects" system which doesn't have this problem: damage is moved into a queue. I'll see if I can back-port a simpler setup up to that point (the easiest would be to have "suffer damage" be a list, with adding damage checking to make the list or append to it).

**Comment by thebracket** [comment]
Those two commits should fix it for all chapters prior to the effects system.

**Comment by NielsRenard** [comment]
Excited to test this when I get home tonight. Will report back

**Comment by NielsRenard** [comment]
Nice clean solution, confirmed fixed :+1: ! Works like a charm, and is definitely worth the little bit of extra complexity.
