### ISSUE TITLE
Chapter 2: Including Specs in the project

### ISSUE THREAD

**Issue by sigfriedmcwild** [thebracket/rustrogueliketutorial#107]
In this section you show the use statements for specs including
```rust
#[macro_use]
extern crate specs_derive;
```
You then go on to explain that this is necessary to import macros. In rust 2018 macros can be imported like other symbols, so this would be sufficient (and avoid the discussion of how ugly `#[macro_use]` is)
```rust
use specs_derive::Component;
```

(this should be supported since rust 1.30, I've just tested it on 1.41.1)

**Comment by thebracket** [comment]
Good catch - thanks for that! I'm working on getting the book corrected.

**Comment by thebracket** [comment]
This should be fixed now. It took a while to find all of the imports to fix!
