### ISSUE TITLE
A* search for groups of mobs freezes the game on certain conditions

### ISSUE THREAD

**Issue by MatteoGgl** [thebracket/rustrogueliketutorial#108]
I'm currently going through the 9th chapter and I noticed the game freezing under certain circumstances; while testing, my conclusion is that the A* algorithm goes through all of the 65536 iterations (defined in `MAX_ASTAR_STEPS`), blocking the game for the duration of the process (at least a minute on my machine). This happens when two or more enemies face a bottleneck, such as a single-tile corridor, and cannot path through each other to go towards the player. Here some screenshots for clarity:

In this first onem the situation causing the hangup is visible; the console is printing algorithm step # for debug purposes.
![blocking_situation_during](https://user-images.githubusercontent.com/16136669/76071915-5c368a00-5f97-11ea-98d3-f5c144ec8010.png)

In this second one the resulting situation: the algorithm has executed all the steps and it's not successful.
![solution_all_steps](https://user-images.githubusercontent.com/16136669/76072045-8f791900-5f97-11ea-93b0-ccf67fdde112.png)

The hangup is caused by the rightmost orc trying to find a path to the player.

**Comment by hammerandtongs** [comment]
I haven't tracked down this bug to this degree but- 

Can confirm that 2-3 clustered mobs on screen leads to semi frequent crashes.

**Comment by MatteoGgl** [comment]
Do you get any error when crashing? I did not get any error, just a very long processing time.

**Comment by hammerandtongs** [comment]
Tbh I've killed it every time since it was a pretty hard hang with no error.

**Comment by RohitJones** [comment]
I can also confirm that I've encountered this issue a couple of times in my play testing, but it is somewhat hard to reproduce consistently.

**Comment by Green-Moblin** [comment]
Did you implement get_pathing_distance for BaseMap? In 1.6 Chasing the Player the tutorial mentions finishing the implementation of BaseMap, but only focuses on implementing get_available_exits.

The source code itself has the following implementation for get_pathing_distance.
https://github.com/thebracket/rustrogueliketutorial/blob/39c3a62741de3ef9b938bc2eef0e1ac8ad79b58b/chapter-07-damage/src/map.rs#L137-L142

A similar issue is also addressed here.
https://github.com/thebracket/rustrogueliketutorial/issues/96#issuecomment-587017071

**Comment by MatteoGgl** [comment]
> Did you implement get_pathing_distance for BaseMap? 

That was definitely the case. After I implemented the function, some quick tests are working perfectly. I'll close this issue for now. Thanks everyone!

**Comment by scottcs** [comment]
I just ran into this, too, and it took quite a while to figure out what was happening. I fixed it before discovering this issue on github, but maybe the issue should remain open so that the tutorial can be made clearer? I think it would save a lot of people time if the tutorial specifically mentions that `get_pathing_distance` needs to be implemented.

**Comment by hammerandtongs** [comment]
Yeah this function isn't documented in the current book and I don't have "get_pathing_distance" in my type along source.

@MatteoGgl I think you should reopen this and change it to request that the function be added to the book.

**Comment by MatteoGgl** [comment]
I wanted to create a new issue, I see @hammerandtongs did that before me =) Thanks!
