### ISSUE TITLE
Section 1.6 Reminder to run new systems

### ISSUE THREAD

**Issue by bendoerr** [thebracket/rustrogueliketutorial#113]
In section 1.6 we add three new systems, `MapIndexingSystem`, `MeleeCombatSystem`, and `DamageSystem`. There is a snippet adding `MapIndexingSystem` to `run_systems`. It would be really helpful to have a quick reminder for `MeleeCombatSystem` and `DamageSystem` to run those similar to how there are reminders when adding a new component. This has been a really fun guide so far, thanks for the hard work of maintaining it!

**Comment by thebracket** [comment]
Thanks! I'll see what I can do. Going a bit more slowly than normal, due to the ISP I work for being REALLY busy with everyone working from home.
