### ISSUE TITLE
Chapter 6: main.rs build? vs. build.unwrap()

### ISSUE THREAD

**Issue by DerekStrickland** [thebracket/rustrogueliketutorial#118]
First of all THANKS!!!!  Super fun project to play with on Saturday mornings with my kids. Now time for a quick observation.

In the tutorial you have 

    let context = RltkBuilder::simple80x50()
        .with_title("Roguelike Tutorial")
        .build()?;

But I get 

cannot use the `?` operator in a function that returns `()`

However if I replace with 

    let context = RltkBuilder::simple80x50()
        .with_title("Roguelike Tutorial")
        .build()
        .unwrap();

I can build and run.  I have updated my Cargo.toml to match all versions you have. I've run rustup update to make sure I'm on the latest stable.  Just curious if you've seen this.  I've got a work around, but it's always nice to stay in since with the mainline.

**Comment by thebracket** [comment]
The signature for `main` also changed: `fn main() -> rltk::BError {` (with the semicolon removed from the `main_loop` call). Unwrapping also works.

I looked at a few chapters (searched for `main`), and it *looks* like I remembered to update the tutorial chapters?

Sorry for the confusion - and I'm really glad you are enjoying the series!

**Comment by DerekStrickland** [comment]
ahhhhhh.... the semicolon was the culprit.  Thx!!!
