### ISSUE TITLE
Should I use new bracket-lib or rltk?

### ISSUE THREAD

**Issue by lqmanh** [thebracket/rustrogueliketutorial#135]
I know that *rltk* was renamed to *bracket-lib* recently and the old *rltk* crate is just a wrapper now.
Then which one should I include as dependency for new projects, when *rltk* is still used everywhere in this tutorial? And if *bracket-lib* is preferred, are there any plan to update the tutorial in a near future?

Thank you in advance!

**Comment by thebracket** [comment]
They are one and the same, and I intend to keep them so. `bracket-lib` is probably a better name (plenty of people are using it for non-Roguelikes now, which was part of the reason for renaming it). I'll be keeping RLTK as a working wrapper. So it doesn't matter. :-)

**Comment by lqmanh** [comment]
Oh thank you for your answer!
