### ISSUE TITLE
Suggestion - maps bigger than the screen

### ISSUE THREAD

**Issue by Zireael07** [thebracket/rustrogueliketutorial#16]
As the topic says. IIRC scrolling maps / camera was one of the bonus parts of the original Roguebasin tutorial.

Also, great job on the Waveform Collapse algorithm! I've been seeing it around various procedural generation sites, but I never could wrap my head around it - and I believe your tutorial cleared it up amazingly!

**Comment by thebracket** [comment]
Thanks! Larger maps with scrolling is actually on my to-do list (I really should share it, but it's pretty fluid), since it's a pretty important topic.

**Comment by thebracket** [comment]
This is now live as Chapter 41!
