### ISSUE TITLE
Chapter 7: Dealing damage,  missing bits

### ISSUE THREAD

**Issue by DominicD** [thebracket/rustrogueliketutorial#17]
Hi again, I am still progressing on your tutorial :)

I found some problems in Chapter 7: (http://bfnightly.bracketproductions.com/rustbook/chapter_7.html) at least I think I did. 
In **Indexing what is where** the method `map.clear_content_index` is called however you never show the implementation. 

In "Expanding the turn system" the gamestate Struct includes `pub systems: Dispatcher<'static, 'static>` which I don't think is introduced yet.

**Comment by thebracket** [comment]
You're right - thank you! The `Dispatcher` is actually some old code from a previous version that needs to be updated (you can use dispatchers with Specs to go multi-threaded, but threads were problematic with web assembly and also for keeping the tutorial simple, so I went away from it). I'll add the missing function to the tutorial text also (it's in the source if you need it in the meantime).

**Comment by thebracket** [comment]
This is fixed now. Thanks for finding it!

**Comment by DominicD** [comment]
Hi thanks again! :)
If I find more stuff would you prefer a pull request? I guess sometimes I could provide it for little things like that.

**Comment by thebracket** [comment]
Either a PR or a bug report is fine. PR's are less work on my part, but I'm just happy that people are reading the tutorial!
