### ISSUE TITLE
Chapter 3.3 Particles Effects : Old Dispatcher code

### ISSUE THREAD

**Issue by FlorentKl** [thebracket/rustrogueliketutorial#19]
Hi ! 
Your guide is really nice ! =)
I just wanted to say that in chapter 3.3 for the particles system, there is still code with DispatcherBuilder, but you don't use anywhere else. It must be some artifacts ?
Thanks !

**Comment by thebracket** [comment]
I'll look for it and get that fixed. Thanks!
