### ISSUE TITLE
build fails on macos

### ISSUE THREAD

**Issue by briangu** [thebracket/rustrogueliketutorial#21]
first attempt with master latest, I get:

```
 ➜  chapter-33-wfc git:(master) cargo build
    Updating crates.io index
    Updating crates.io index
error: no matching package named `rusttype_next` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `rusttype v0.7.9`
    ... which is depended on by `andrew v0.2.1`
    ... which is depended on by `smithay-client-toolkit v0.6.4`
    ... which is depended on by `winit v0.20.0-alpha3`
    ... which is depended on by `glutin v0.22.0-alpha3`
    ... which is depended on by `rltk v0.5.1 (https://github.com/thebracket/rltk_rs#30ef14b8)`
    ... which is depended on by `chapter-39-halls v0.1.0 (/Users/brian.guarraci/code/rustrogueliketutorial/chapter-39-halls)`

```

after running 

```cargo update```
```cargo build```

I get

```
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/brian.guarraci/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.3/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

```cargo --version```
```
➜  chapter-33-wfc git:(master) ✗ cargo --version
cargo 1.30.0 (36d96825d 2018-10-24)
```

**Comment by thebracket** [comment]
Thanks for the report! It may take me a little bit to get hold of a Mac to test on, but I'll see if I can figure out the crate issue. It looks like something snarled up in the "hashbrown" crate (unfortunately, that's used by Specs, rather than my code). It really shouldn't require the nightly version of Rust!

**Comment by thebracket** [comment]
I've *finally* got myself a working Mac VM to test with, so I'll start work on this. Sorry it took so long to get going!

**Comment by thebracket** [comment]
I can't seem to replicate this. I installed a Rust toolchain via rust.rs, cloned and ran `cargo test` - and everything compiled and ran.

I do have a different error; running the examples in OpenGL mode gives a "no available pixel format" error, but I'm in a non-accelerated VM so I'll have to do some tweaking to test that.

**Comment by briangu** [comment]
thanks for looking into this!  i just refetched the latest rust toolchain it indeed it does work now.  I wonder if there was just a period of time where the toolchain was in a broken state.
