### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Zireael07** [thebracket/rustrogueliketutorial#24]
There's a couple of persistent typos in code across the whole tutorial.

- [ ] "voroni_distance" when talking about the Voronoi Hive Map (chapter 3.10 and onwards)
- [ ] "cellular_autom_o_ta" (chapter 3.5 and onwards) - both the file name (!) and the class name, while the tutorial header correctly spells it as automAta

**Comment by thebracket** [comment]
Thanks! I'll try and get those fixed. You've happened upon the two that my brain consistently refuses to spell properly (I blame age)!

**Comment by thebracket** [comment]
I believe that takes care of that. Thanks!
