### ISSUE TITLE
Chapter 1.5 - unused code referenced

### ISSUE THREAD

**Issue by tylervipond** [thebracket/rustrogueliketutorial#26]
In https://bfnightly.bracketproductions.com/rustbook/chapter_6.html#making-the-monsters-think there is a note regarding `&["visibility_system"]` which isn't actually used in the code example up to that point, unless I've somehow missed it, which is possible. 

Also, in https://bfnightly.bracketproductions.com/rustbook/chapter_6.html#turn-based-ga me-in-a-tick-based-world there is a reference to using the `RunState` enum in our `run_systems` function, but that isn't reflected in the code example.

Great tutorial series!

**Comment by thebracket** [comment]
Good catch. That was a hangover from a bit of code that got removed for WASM support. Thanks!
