### ISSUE TITLE
2 issues via Twitter (thanks @JpMoresmau)

### ISSUE THREAD

**Issue by thebracket** [thebracket/rustrogueliketutorial#27]
:  at http://bfnightly.bracketproductions.com/rustbook/chapter_6.html#turn-based-game-in-a-tick-based-world: you add a RunState enum, fine, and you say you add it to run_systems, I don't see it in the code.

 at http://bfnightly.bracketproductions.com/rustbook/chapter_6.html#turn-based-game-in-a-tick-based-world: just before the chapter, you mention &["visibility_system"] but I don't see it in the code

**Comment by JPMoresmau** [comment]
Duplicate of #26.

**Comment by thebracket** [comment]
You're right. Sorry - I _really_ should drink my coffee before I hit the bug list!
