### ISSUE TITLE
Chapter 7: player can move over monsters

### ISSUE THREAD

**Issue by JPMoresmau** [thebracket/rustrogueliketutorial#29]
Half way through Chapter 7 (dealing damage) the player can move over monsters!! This is because I think of the order we run systems in:
- the player move
- we run map_indexing
- we run monster_ai
- the player moves again

So when the player moves, map_indexing has not been refreshed with the new monster positions. I've solved it by changing the order in run_systems:

```
fn run_systems(&mut self) {
        let mut vis = VisibilitySystem{};
        vis.run_now(&self.ecs);
        let mut mob = MonsterAI{};
        mob.run_now(&self.ecs);
        let mut mapindex = MapIndexingSystem{};
        mapindex.run_now(&self.ecs);
        self.ecs.maintain();
    }
```
_Originally posted by @Zireael07 in https://github.com/thebracket/rustrogueliketutorial/issues/28#issuecomment-552125591_

**Comment by Zireael07** [comment]
Yeah, this fixes the issue - I just checked.
