### ISSUE TITLE
Chapter 1.8 - potions heal to max instead of their heal_amount

### ISSUE THREAD

**Issue by Zireael07** [thebracket/rustrogueliketutorial#30]
The culprit is this line: `stats.hp = i32::max(stats.max_hp, stats.hp + potion.heal_amount);` in PotionUseSystem (inventory_system.rs)

Changing the i32::max to i32::min fixes the issue.

**Comment by thebracket** [comment]
I actually found this bug and forgot to back-port the fix. It mysteriously fixes itself in a later chapter as a result. Thanks for the reminder - fixing it now.
