### ISSUE TITLE
Section 1.6 duplicate code

### ISSUE THREAD

**Issue by tylervipond** [thebracket/rustrogueliketutorial#31]
I'm not sure if you would like to consider this an issue or not, but I noticed that in the chapter on taking damage, in the first code example we have the code:
```rust
let idx = (y * self.width) + x;
self.tiles[idx as usize] != TileType::Wall
```
which works. However we actually already have a function for this with `self.xy_idx`,
so this could be:
```rust
let idx = self.xy_idx(x, y);
self.tiles[idx] != TileType::Wall
```
which is nice because we wouldn't have to cast to usize in the second line and we would be connecting the code to that helper function from earlier chapters. Again, not really sure this is an issue or not, I just thought I'd mention it.

**Comment by thebracket** [comment]
Good spot - thanks! I'll see what I can do about incorporating it and getting you into the contributors list.
