### ISSUE TITLE
Seciton 1.6 example - description mismatch

### ISSUE THREAD

**Issue by tylervipond** [thebracket/rustrogueliketutorial#35]
In section 1.6 towards the end of this [sub-section on blocking access](http://bfnightly.bracketproductions.com/rustbook/chapter_7.html#blocking-access) there is a line that reads: "We do however add it to the dependency list for MonsterAI - the AI relies on its results, so it has to be done.", but none of the examples in the section seem to add `MapIndexingSystem` as a dependency of `MonsterAI`, it's possible I just missed it though.

**Comment by thebracket** [comment]
I'll see about getting this merged. Having a poor day in terms of code I write actually working, so I may belay this until the weekend or Monday!
