### ISSUE TITLE
"Out of bounds" walking freezes the game

### ISSUE THREAD

**Issue by kikito** [thebracket/rustrogueliketutorial#38]
# Short description

Exiting the map is possible, and provokes a freeze

# Where

It is present in [Chapter 61 / 4.18](http://bfnightly.bracketproductions.com/rustbook/chapter_61.html). I believe this was introduced in [Chapter 47 / 4.4](http://bfnightly.bracketproductions.com/rustbook/chapter_47.html). I have not tried previous Sections.

# Steps to reproduce:

[Start the game](http://bfnightly.bracketproductions.com/rustbook/wasm/chapter-61-townportal/). Exit the initial tavern, and go to the beach (usually to the left). Once at the beach, it's possible to exit the map by walking north or south. When this happens, the game freezes.

# Expected result:

I suspect this particular case could be solved by tweaking the algorithm which generates the beach (just ensure north and south endings are surrounded by deep water). But this problem will surely appear again in other places. I suggest fixing the walking subroutine so that the player isn't able to step out of the map.

Bonus point to adding a message like if the player attempts it. Super-bonus points if the quote is context-aware. For example in the beach it could say: "Hey, do you know the way to [Shell Beach](https://www.youtube.com/watch?v=hNMZGSzB7EI)?".

**Comment by Zireael07** [comment]
It's introduced sometime even earlier than that, I had it occasionally as early as section 1 of the tutorial. At some point however, it seems to have stopped, but I'm not sure what fixed it. I will try to look through my code to figure it out.

**Comment by thebracket** [comment]
I'll see what I can do. I need to rework the bounds-checking (we do it all the time, it should be a robust function); I'll try and get to that in the next couple of days. I've made a start by adding an `in_bounds` optional function to the map trait it RLTK (which lets me make the various algorithms bounds-aware and trim out a lot of dross!)
