### ISSUE TITLE
Typo in WFC tutorial

### ISSUE THREAD

**Issue by toyboot4e** [thebracket/rustrogueliketutorial#42]
Thank you for your well-written tutorial!

- Typo in the waveform collapse tutorial: `pub fn patterns_to_constaints` should be `pub fn patterns_to_constraints`.

- Just my curious, but why do you refer to it as "waveform collapse", not "wave function collapse"?

- Also, this code in the function (`patterns_to_constaints`)

```rust
                    let opposite;
                    match direction {
                        0 => opposite = 1, // Our North, Their South
                        1 => opposite = 0, // Our South, Their North
                        2 => opposite = 3, // Our West, Their East
                        _ => opposite = 2 // Our East, Their West
                    }
```

may be written as

```rust
                    let opposite = match direction {
                        0 => 1, // Our North, Their South
                        1 => 0, // Our South, Their North
                        2 => 3, // Our West, Their East
                        _ => 2, // Our East, Their West
                    };
```

**Comment by thebracket** [comment]
You're right, it really should be "wave function collapse" rather than "waveform collapse". I saw it as the former once and the name stuck, unfortunately I've repeated the error EVERYWHERE so it may take some time to fix!
