### ISSUE TITLE
Chapter 9 undefined constants

### ISSUE THREAD

**Issue by tylervipond** [thebracket/rustrogueliketutorial#47]
In the section [Spawn All the Things](http://bfnightly.bracketproductions.com/rustbook/chapter_9.html#spawn-all-the-things) There's a reference to `MAX_MONSTERS` but this hasn't been defined as far as I know, and it's not mentioned yet in the tutorial. Same for `MAX_ITEMS` which is introduced in [Health Potion Entities](http://bfnightly.bracketproductions.com/rustbook/chapter_9.html#health-potion-entities). Obviously it's easy to fill in the blanks, just thought I'd mention it. Great tutorial Series!

**Comment by thebracket** [comment]
I'll see about getting the wording fixed to mention this - thanks!
