### ISSUE TITLE
Chapter 11 sometimes crashes on while loading

### ISSUE THREAD

**Issue by Kawzeg** [thebracket/rustrogueliketutorial#50]
The Saveload system introduced in chapter 11 sometimes creates corrupt savegames that cause a crash on deserialization, like [this one](https://pastebin.com/vp9c9uCq). I can't reproduce it all the time, but starting a new game, quitting, restarting, and then loading a few times often does it.

The actual crash occurs on line 118 of `saveload_system.rs`:
```rust
ecs.delete_entity(deleteme.unwrap()).expect("Unable to delete helper");
```

It crashes because `deleteme` is never set. `deleteme` stays `None` because the marker id of the `SerializationHelper` is duplicated in the savegame (`{"marker":[10],"components":[{"map":{"tiles":...` in the linked savegame, note that there is also `{"marker":[10],"components":[null]}`, 

I still don't fully understand the serialization/deserialization of entities, but I think the issue is that the existing marker allocator is not used on deserialization, which leads to duplicate entity ids on serialization. Instead, a new allocator is created in line 90:

```
&mut SimpleMarkerAllocator::<SerializeMe>::new()
```

Reusing the existing allocator with `&mut ecs.write_resource::<SimpleMarkerAllocator<SerializeMe>>()` seems to fix the issue.

**Comment by thebracket** [comment]
I'll do some testing, but I think you're right. The serialization story with Specs/Serde is a bit more of a mess than I'd like; it's *almost* seamless, and then Entity implementation makes it all confusing! (I've always just used an integer for entities in my ECS designs for that reason!)

**Comment by Kawzeg** [comment]
On a related note, is it actually necessary to implement the `ConvertSaveload` trait here instead of using `derive(ConvertSaveload)`? It seems to compile fine, but I haven't tested it much more than that. Derive macros are total black magic for me at the moment, so I can't really tell what it's actually doing.

Really appreciate the work you're putting into this btw, it's a great excuse & resource to learn rust :)

**Comment by thebracket** [comment]
Woah, there's a derive macro for `ConvertSaveload`? I didn't see that back when I first implemented it! If that works, it'd save a TON of effort!

**Comment by Kawzeg** [comment]
Yeah, although the [docs](https://docs.rs/specs/0.14.3/specs/saveload/trait.ConvertSaveload.html) say it's called `derive(Saveload)`, it's actually `derive(ConvertSaveload)` (The actual definition at https://github.com/amethyst/specs/blob/master/specs-derive/src/lib.rs)

**Comment by thebracket** [comment]
I messed up the commit message, but https://github.com/thebracket/rustrogueliketutorial/commit/c9eeda6d563d7262b4b6c0a0107f8771af2b17f6 provides the basic fix. I'd like to do more with the derive components and work on the chapter a bit, so I'm leaving this open.
