### ISSUE TITLE
Ch 9 - Picking Up Items component defs not consistent with source.

### ISSUE THREAD

**Issue by dethmuffin** [thebracket/rustrogueliketutorial#62]
https://github.com/thebracket/rustrogueliketutorial/blob/master/book/src/chapter_9.md#picking-up-items

Removed ConvertSaveload from the derives for InBackpack and WantsToPickupItem components (just like the source for this chapter)

**Comment by thebracket** [comment]
Thanks! I'll get this some attention. The "ConvertSaveLoad" change made quite a mess, I hoped I'd got it all (but Specs providing that saved a TON of pages!)
