### ISSUE TITLE
Duplicate objects since chapter 3.14

### ISSUE THREAD

**Issue by FlorentKl** [thebracket/rustrogueliketutorial#63]
Hello,
I have seen since chapter 3.14 to at least the chapter 4.3 that all objects and monsters are duplicated upon spawn. 
Trying to narrow down the problem, i found it coming from the function "apply_previous_iteration" in "src\map_builders\prefab_builder\mod.rs" : the part `if filter(x, y, e) {
  build_data.spawn_list.push(
   (idx, e.1.to_string())
  )
}` totally duplicate the spawn list. 

When using `!filter`, it seems back to normal, exept if there is a sectionnal fort where items are in two copies, but i don't have a good enough grasp on the filter function to know what to do or if what i have done is the right solution.

**Comment by thebracket** [comment]
Whoops! Thanks for reporting that. I haven't seen it on my local build, but so I probably fixed it by mistake somewhere further down the line. I'll take a look.
