### ISSUE TITLE
Some resources has wrong extensions

### ISSUE THREAD

**Issue by zerocity** [thebracket/rustrogueliketutorial#67]
Hi ,

in the implementation of Rltk::init_simple8x8 

```rust
let font_path = format!("{}/terminal8x8.png", &path_to_shaders.to_string());
```

but in the resources, the files have extensions of .jpg

i dont get any error and the game dont crashes.

**Comment by thebracket** [comment]
This is a fun example of "good intentions gone awry". I fixed up RLTK to work with PNGs, and forgot to update the tutorial to match. HOWEVER - RLTK knows about a couple of default fonts and automatically includes them in the build (this makes web building easier, and avoids some pathing problems on various systems). So it stealthily fixed itself.

I'll try and clarify the language to match and update the extensions. Thanks!
