### ISSUE TITLE
SSL Certificate for bfnightly.bracketproductions.com expired

### ISSUE THREAD

**Issue by joguSD** [thebracket/rustrogueliketutorial#74]
Was going through the tutorials last night when the certificate expiration hit 1/14/2020.

**Comment by thebracket** [comment]
Oops! It turns out that *Let's Encrypt* update scripts work better when you actually remember to add them to cron. Fixing that up now - thanks!

**Comment by thebracket** [comment]
This should be fixed now. It turns out it *was* in cron, but the cert system was trying to auto-upgrade, and the security settings on that box didn't allow it.

**Comment by thebracket** [comment]
Ok, I've received confirmation that it works outside of my admin network. Thanks again!
