### ISSUE TITLE
Chapter 3.11 mention the model of WFC 

### ISSUE THREAD

**Issue by toyboot4e** [thebracket/rustrogueliketutorial#82]
[3.11 Wave Function Collapse](http://bfnightly.bracketproductions.com/rustbook/chapter_33.html)

The official [WFC repo](https://github.com/mxgmn/WaveFunctionCollapse) has two models: [SimpleTiledModel](https://github.com/mxgmn/WaveFunctionCollapse/blob/master/SimpleTiledModel.cs) and [OverlappingModel](https://github.com/mxgmn/WaveFunctionCollapse/blob/master/OverlappingModel.cs). And it looks like the former is implemented in the book. But today, "WFC" tends to refer to the latter model, so it might be a bit confusing to those who are new to WFC.

Then I suggest stating that there are two models, and  that the OverlappingModel is not explained in the book. It may be helpful to readers who also want to read other resources about WFC (like me :)).

Note: the SimpleTiledModel forces that any adjacent chunks are compatible. While the OverlappingModel forces that any overlapping chunks are compatible.

Edit: Sorry, it was misleading. Actually, your WFC is not exactly a SimpleTiledModel. It may be more like a hybrid of the two models. You collect chunks from the source (not from xml), but you place them based on adjacency (not on local similarity). So there are two kind of constraints to fullfill the map, and you explained one of them. I guess that's worth mentioning!

**Comment by thebracket** [comment]
I'll see if I can clarify. I ended up using adjacency because it is more likely to give a working map (similarity is great, but without an understanding of traversability you can get beautiful - but unreachable - maps). Thanks!

**Comment by toyboot4e** [comment]
Yes, and I like your credible implementation. It produces connected maps, and it works MUCH faster than the OverlappingModel. And the idea of using small chunks is very appealing.
