### ISSUE TITLE
Chapter 1.7 - Tooltip revealing monsters and items on invisible tiles.

### ISSUE THREAD

**Issue by pprobst** [thebracket/rustrogueliketutorial#87]
Hello,

In [Chapter 1.7 - User interface](https://bfnightly.bracketproductions.com/rustbook/chapter_8.html), tooltip support was added. However, there's a bug regarding its functionality: the tooltip box is appearing when we pass the mouse over items or monsters on invisible tiles -- this can be observed in the WASM version, so the code I wrote is not at fault. I've just done chapter 1.8 and the problem persists, so I guess it just passed without being noticed.

Thankfully this problem is easily solved by having a check on whether the mouse position is in a visible tile of the map or not when you populate the tooltip vector in `fn draw_tooltips` (`gui.rs`). It's easy to solve, but I guess it's worth being reported anyways!

**Comment by thebracket** [comment]
This fix for this is:
```rust
for (name, position) in (&names, &positions).join() {
    let idx = map.xy_idx(position.x, position.y);
    if position.x == mouse_pos.0 && position.y == mouse_pos.1 && map.revealed_tiles[idx] {
        tooltip.push(name.name.to_string());
    }
}
```
The tutorial and associated code are updating now.

**Comment by pprobst** [comment]
Wouldn't that be `&& map.visible_tiles[idx]`?
If I'm not mistaken, just checking the revealed tiles will stil show enemies that are not in the player's viewshed, as the revealed tiles are the "grayed out" areas that the player has already explored but not necessarily visible.

**Comment by thebracket** [comment]
Doh! You're right. I'll get it re-fixed!
