### ISSUE TITLE
Section 1.10 unnecessary instruction

### ISSUE THREAD

**Issue by tylervipond** [thebracket/rustrogueliketutorial#95]
In the [Getting Started With Saving](http://bfnightly.bracketproductions.com/rustbook/chapter_11.html#getting-started-with-saving-the-game) part of section 1.10 it looks like the last code example and the preceding instruction above are not necessary as they are actually covered in the first code example and it's preceding instruction.

**Comment by thebracket** [comment]
Good catch, thanks! I'll be uploading a fixed version shortly.
